DOCKER_IMAGE ?= nbd-server-dev:local
DOCKER_CONTAINER ?= nbd-server-dev
DOCKER_PLATFORM ?= linux/arm64
DOCKER_WORKDIR ?= /work
DOCKER_CARGO_TARGET_DIR ?= /cargo-target
DOCKER_INTERACTIVE_FLAGS ?= -it
DOCKER_PATH := $(DOCKER_CARGO_TARGET_DIR)/debug:/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NBD_DEVICE_SMOKE_OUTPUT ?= $(if $(KERNEL_SMOKE_OUTPUT),$(KERNEL_SMOKE_OUTPUT),docker-smoke)
DOCKER_NBD_DEVICE_SMOKE_ARTIFACT_DIR ?= $(if $(DOCKER_KERNEL_SMOKE_ARTIFACT_DIR),$(DOCKER_KERNEL_SMOKE_ARTIFACT_DIR),$(CURDIR)/.tmp/$(NBD_DEVICE_SMOKE_OUTPUT))
DOCKER_NBD_DEVICE_SMOKE_ARTIFACT_MOUNT ?= $(if $(DOCKER_KERNEL_SMOKE_ARTIFACT_MOUNT),$(DOCKER_KERNEL_SMOKE_ARTIFACT_MOUNT),/tmp/nbd-device-smoke-artifacts)
NBD_DEVICE_SMOKE_EFFECTIVE_ENGINE = $(if $(NBD_DEVICE_SMOKE_ENGINE),$(NBD_DEVICE_SMOKE_ENGINE),$(if $(KERNEL_SMOKE_ENGINE),$(KERNEL_SMOKE_ENGINE),wal_durable))
NBD_DEVICE_SMOKE_EFFECTIVE_SCENARIO = $(if $(NBD_DEVICE_SMOKE_SCENARIO),$(NBD_DEVICE_SMOKE_SCENARIO),$(if $(KERNEL_SMOKE_SCENARIO),$(KERNEL_SMOKE_SCENARIO),$(if $(filter memory,$(NBD_DEVICE_SMOKE_EFFECTIVE_ENGINE)),memory-basic,$(if $(filter simple_durable simple-durable,$(NBD_DEVICE_SMOKE_EFFECTIVE_ENGINE)),simple-durable-basic,$(if $(filter wal_durable wal-durable,$(NBD_DEVICE_SMOKE_EFFECTIVE_ENGINE)),wal-durable-basic,unknown)))))
RUSTFS_IMAGE ?= rustfs/rustfs:1.0.0-alpha.94-glibc
DOCKER_SMOKE_S3_NETWORK ?= nbd-smoke-s3-e2e
DOCKER_SMOKE_S3_RUSTFS_CONTAINER ?= nbd-smoke-s3-e2e-rustfs
DOCKER_SMOKE_S3_RUSTFS_ALIAS ?= rustfs
DOCKER_SMOKE_S3_RUSTFS_VOLUME ?= nbd-smoke-s3-e2e-rustfs-data
DOCKER_SMOKE_S3_ARTIFACT_DIR ?= $(CURDIR)/.tmp/docker-smoke-s3
DOCKER_SMOKE_S3_ACCESS_KEY ?= rustfsadmin
DOCKER_SMOKE_S3_SECRET_KEY ?= rustfsadmin
DOCKER_SMOKE_S3_BUCKET ?= everstore
DOCKER_SMOKE_S3_KEY_PREFIX ?= v0.1/blobs/
DOCKER_RUSTFS_NETWORK ?= nbd-rustfs-dev
DOCKER_RUSTFS_CONTAINER ?= nbd-rustfs-dev
DOCKER_RUSTFS_ALIAS ?= rustfs
DOCKER_RUSTFS_VOLUME ?= nbd-rustfs-dev-data
DOCKER_RUSTFS_PORT ?= 9000
DOCKER_RUSTFS_CONSOLE_PORT ?= 9001

DOCKER_RUN_BASE = docker run --rm \
	--platform $(DOCKER_PLATFORM)

DOCKER_RUN_NAMED = $(DOCKER_RUN_BASE) \
	--name $(DOCKER_CONTAINER)

DOCKER_WORKSPACE_ARGS = \
	-v "$(CURDIR):$(DOCKER_WORKDIR)" \
	-v nbd-cargo-registry:/usr/local/cargo/registry \
	-v nbd-cargo-git:/usr/local/cargo/git \
	-v nbd-cargo-target:$(DOCKER_CARGO_TARGET_DIR) \
	-e CARGO_TARGET_DIR=$(DOCKER_CARGO_TARGET_DIR) \
	-e PATH=$(DOCKER_PATH) \
	-w $(DOCKER_WORKDIR)

DOCKER_WORKSPACE_READONLY_ARGS = \
	-v "$(CURDIR):$(DOCKER_WORKDIR):ro" \
	-v nbd-cargo-registry:/usr/local/cargo/registry \
	-v nbd-cargo-git:/usr/local/cargo/git \
	-v nbd-cargo-target:$(DOCKER_CARGO_TARGET_DIR) \
	-e CARGO_TARGET_DIR=$(DOCKER_CARGO_TARGET_DIR) \
	-e PATH=$(DOCKER_PATH) \
	-w $(DOCKER_WORKDIR)

DOCKER_RUN_WORKSPACE = $(DOCKER_RUN_BASE) $(DOCKER_WORKSPACE_ARGS)
DOCKER_RUN_WORKSPACE_NAMED = $(DOCKER_RUN_NAMED) $(DOCKER_WORKSPACE_ARGS)
DOCKER_RUN_WORKSPACE_READONLY = $(DOCKER_RUN_BASE) $(DOCKER_WORKSPACE_READONLY_ARGS)
DOCKER_RUN = $(DOCKER_RUN_WORKSPACE) $(DOCKER_IMAGE)
DOCKER_SMOKE_S3_ENV = \
	-e NBD_TEST_S3_ENDPOINT_URL=http://$(DOCKER_SMOKE_S3_RUSTFS_ALIAS):9000 \
	-e NBD_TEST_S3_BUCKET=$(DOCKER_SMOKE_S3_BUCKET) \
	-e NBD_TEST_S3_ACCESS_KEY_ID=$(DOCKER_SMOKE_S3_ACCESS_KEY) \
	-e NBD_TEST_S3_SECRET_ACCESS_KEY=$(DOCKER_SMOKE_S3_SECRET_KEY) \
	-e NBD_TEST_S3_REGION=us-east-1 \
	-e NBD_TEST_S3_KEY_PREFIX=$(DOCKER_SMOKE_S3_KEY_PREFIX)
DOCKER_RUSTFS_SHELL_ENV = \
	-e NBD_TEST_S3_ENDPOINT_URL=http://$(DOCKER_RUSTFS_ALIAS):9000 \
	-e NBD_TEST_S3_BUCKET=$(DOCKER_SMOKE_S3_BUCKET) \
	-e NBD_TEST_S3_ACCESS_KEY_ID=$(DOCKER_SMOKE_S3_ACCESS_KEY) \
	-e NBD_TEST_S3_SECRET_ACCESS_KEY=$(DOCKER_SMOKE_S3_SECRET_KEY) \
	-e NBD_TEST_S3_REGION=us-east-1 \
	-e NBD_TEST_S3_KEY_PREFIX=$(DOCKER_SMOKE_S3_KEY_PREFIX)
DOCKER_SMOKE_COMMON_ENV = \
	REPO_ROOT="$(CURDIR)" \
	DOCKER_IMAGE="$(DOCKER_IMAGE)" \
	DOCKER_PLATFORM="$(DOCKER_PLATFORM)" \
	DOCKER_WORKDIR="$(DOCKER_WORKDIR)" \
	DOCKER_CARGO_TARGET_DIR="$(DOCKER_CARGO_TARGET_DIR)" \
	DOCKER_PATH="$(DOCKER_PATH)" \
	DOCKER_NBD_DEVICE_SMOKE_ARTIFACT_DIR="$(DOCKER_NBD_DEVICE_SMOKE_ARTIFACT_DIR)" \
	DOCKER_NBD_DEVICE_SMOKE_ARTIFACT_MOUNT="$(DOCKER_NBD_DEVICE_SMOKE_ARTIFACT_MOUNT)" \
	VERBOSE="$(VERBOSE)"
DOCKER_SMOKE_NBD_DEVICE_ENV = \
	NBD_DEVICE_SMOKE_EXPORT="$(if $(NBD_DEVICE_SMOKE_EXPORT),$(NBD_DEVICE_SMOKE_EXPORT),$(KERNEL_SMOKE_EXPORT))" \
	NBD_DEVICE_SMOKE_SCENARIO="$(if $(NBD_DEVICE_SMOKE_SCENARIO),$(NBD_DEVICE_SMOKE_SCENARIO),$(KERNEL_SMOKE_SCENARIO))" \
	NBD_DEVICE_SMOKE_SIZE_BYTES="$(if $(NBD_DEVICE_SMOKE_SIZE_BYTES),$(NBD_DEVICE_SMOKE_SIZE_BYTES),$(KERNEL_SMOKE_SIZE_BYTES))" \
	NBD_DEVICE_SMOKE_ENGINE="$(if $(NBD_DEVICE_SMOKE_ENGINE),$(NBD_DEVICE_SMOKE_ENGINE),$(KERNEL_SMOKE_ENGINE))" \
	NBD_DEVICE_SMOKE_CARGO_FEATURES="$(if $(NBD_DEVICE_SMOKE_CARGO_FEATURES),$(NBD_DEVICE_SMOKE_CARGO_FEATURES),$(KERNEL_SMOKE_CARGO_FEATURES))" \
	NBD_DEVICE_SMOKE_PORT="$(if $(NBD_DEVICE_SMOKE_PORT),$(NBD_DEVICE_SMOKE_PORT),$(KERNEL_SMOKE_PORT))" \
	NBD_DEVICE_SMOKE_DEVICE="$(if $(NBD_DEVICE_SMOKE_DEVICE),$(NBD_DEVICE_SMOKE_DEVICE),$(KERNEL_SMOKE_DEVICE))" \
	NBD_DEVICE_SMOKE_RUST_LOG="$(if $(NBD_DEVICE_SMOKE_RUST_LOG),$(NBD_DEVICE_SMOKE_RUST_LOG),$(KERNEL_SMOKE_RUST_LOG))" \
	NBD_DEVICE_SMOKE_S3_ENDPOINT_URL="$(if $(NBD_DEVICE_SMOKE_S3_ENDPOINT_URL),$(NBD_DEVICE_SMOKE_S3_ENDPOINT_URL),$(KERNEL_SMOKE_S3_ENDPOINT_URL))" \
	NBD_DEVICE_SMOKE_S3_BUCKET="$(if $(NBD_DEVICE_SMOKE_S3_BUCKET),$(NBD_DEVICE_SMOKE_S3_BUCKET),$(KERNEL_SMOKE_S3_BUCKET))" \
	NBD_DEVICE_SMOKE_S3_ACCESS_KEY_ID="$(if $(NBD_DEVICE_SMOKE_S3_ACCESS_KEY_ID),$(NBD_DEVICE_SMOKE_S3_ACCESS_KEY_ID),$(KERNEL_SMOKE_S3_ACCESS_KEY_ID))" \
	NBD_DEVICE_SMOKE_S3_SECRET_ACCESS_KEY="$(if $(NBD_DEVICE_SMOKE_S3_SECRET_ACCESS_KEY),$(NBD_DEVICE_SMOKE_S3_SECRET_ACCESS_KEY),$(KERNEL_SMOKE_S3_SECRET_ACCESS_KEY))" \
	NBD_DEVICE_SMOKE_S3_REGION="$(if $(NBD_DEVICE_SMOKE_S3_REGION),$(NBD_DEVICE_SMOKE_S3_REGION),$(KERNEL_SMOKE_S3_REGION))" \
	NBD_DEVICE_SMOKE_S3_KEY_PREFIX="$(if $(NBD_DEVICE_SMOKE_S3_KEY_PREFIX),$(NBD_DEVICE_SMOKE_S3_KEY_PREFIX),$(KERNEL_SMOKE_S3_KEY_PREFIX))" \
	NBD_DEVICE_SMOKE_COMPACTION_SETTLE_SECONDS="$(if $(NBD_DEVICE_SMOKE_COMPACTION_SETTLE_SECONDS),$(NBD_DEVICE_SMOKE_COMPACTION_SETTLE_SECONDS),$(KERNEL_SMOKE_COMPACTION_SETTLE_SECONDS))"
DOCKER_SMOKE_S3_SCRIPT_ENV = \
	RUSTFS_IMAGE="$(RUSTFS_IMAGE)" \
	DOCKER_SMOKE_S3_NETWORK="$(DOCKER_SMOKE_S3_NETWORK)" \
	DOCKER_SMOKE_S3_RUSTFS_CONTAINER="$(DOCKER_SMOKE_S3_RUSTFS_CONTAINER)" \
	DOCKER_SMOKE_S3_RUSTFS_ALIAS="$(DOCKER_SMOKE_S3_RUSTFS_ALIAS)" \
	DOCKER_SMOKE_S3_RUSTFS_VOLUME="$(DOCKER_SMOKE_S3_RUSTFS_VOLUME)" \
	DOCKER_SMOKE_S3_ARTIFACT_DIR="$(DOCKER_SMOKE_S3_ARTIFACT_DIR)" \
	DOCKER_SMOKE_S3_ACCESS_KEY="$(DOCKER_SMOKE_S3_ACCESS_KEY)" \
	DOCKER_SMOKE_S3_SECRET_KEY="$(DOCKER_SMOKE_S3_SECRET_KEY)" \
	DOCKER_SMOKE_S3_BUCKET="$(DOCKER_SMOKE_S3_BUCKET)" \
	DOCKER_SMOKE_S3_KEY_PREFIX="$(DOCKER_SMOKE_S3_KEY_PREFIX)" \
	DOCKER_SMOKE_S3_REGION="$(DOCKER_SMOKE_S3_REGION)" \
	KEEP_RUSTFS="$(KEEP_RUSTFS)"

.PHONY: test test-protocol fmt clippy build docker-build docker-test \
	docker-shell docker-kernel-shell docker-attach docker-smoke docker-stop \
	docker-rustfs-up docker-rustfs-down docker-smoke-s3-down \
	docker-rustfs-s3-test docker-smoke-s3-probe docker-smoke-s3 \
	nbd-device-smoke-inner kernel-smoke-inner

test:
	cargo test --workspace

test-protocol:
	cargo test -p nbd-server --test tcp_integration

fmt:
	cargo fmt --all

clippy:
	cargo clippy --workspace --all-targets -- -D warnings

build:
	cargo build -p nbd-server -p nbdcli

docker-build:
	docker buildx build \
		--platform $(DOCKER_PLATFORM) \
		-t $(DOCKER_IMAGE) \
		-f docker/Dockerfile \
		--load \
		.

docker-test: docker-build
	$(DOCKER_RUN) sh -lc 'make test && make fmt && make clippy'

docker-shell: docker-build
	$(DOCKER_RUN_WORKSPACE_NAMED) $(DOCKER_INTERACTIVE_FLAGS) $(DOCKER_IMAGE) bash

docker-kernel-shell: docker-build docker-rustfs-up
	$(DOCKER_RUN_WORKSPACE_NAMED) $(DOCKER_INTERACTIVE_FLAGS) \
		--network $(DOCKER_RUSTFS_NETWORK) \
		$(DOCKER_RUSTFS_SHELL_ENV) \
		--privileged $(DOCKER_IMAGE) bash

docker-attach:
	docker exec $(DOCKER_INTERACTIVE_FLAGS) -w $(DOCKER_WORKDIR) \
		$(DOCKER_CONTAINER) bash

docker-smoke:
	@$(DOCKER_SMOKE_COMMON_ENV) \
		$(DOCKER_SMOKE_NBD_DEVICE_ENV) \
		bash scripts/docker/docker-smoke.sh

docker-stop:
	-docker rm -f $(DOCKER_CONTAINER)

docker-rustfs-up:
	@echo "starting RustFS dev sidecar:"
	@echo "  image: $(RUSTFS_IMAGE)"
	@echo "  network: $(DOCKER_RUSTFS_NETWORK)"
	@echo "  container: $(DOCKER_RUSTFS_CONTAINER)"
	@docker network inspect $(DOCKER_RUSTFS_NETWORK) >/dev/null 2>&1 || \
		docker network create $(DOCKER_RUSTFS_NETWORK) >/dev/null
	@docker volume inspect $(DOCKER_RUSTFS_VOLUME) >/dev/null 2>&1 || \
		docker volume create $(DOCKER_RUSTFS_VOLUME) >/dev/null
	@if docker inspect $(DOCKER_RUSTFS_CONTAINER) >/dev/null 2>&1; then \
		docker start $(DOCKER_RUSTFS_CONTAINER) >/dev/null; \
	else \
		docker run -d \
			--name $(DOCKER_RUSTFS_CONTAINER) \
			--network $(DOCKER_RUSTFS_NETWORK) \
			--network-alias $(DOCKER_RUSTFS_ALIAS) \
			-p $(DOCKER_RUSTFS_PORT):9000 \
			-p $(DOCKER_RUSTFS_CONSOLE_PORT):9001 \
			-v $(DOCKER_RUSTFS_VOLUME):/data \
			-e RUSTFS_ACCESS_KEY=$(DOCKER_SMOKE_S3_ACCESS_KEY) \
			-e RUSTFS_SECRET_KEY=$(DOCKER_SMOKE_S3_SECRET_KEY) \
			-e RUSTFS_ADDRESS=:9000 \
			$(RUSTFS_IMAGE) /data >/dev/null; \
	fi
	@echo "RustFS endpoint: http://localhost:$(DOCKER_RUSTFS_PORT)"
	@echo "cleanup: make docker-rustfs-down"

docker-rustfs-down:
	-docker rm -f $(DOCKER_RUSTFS_CONTAINER)
	-docker network rm $(DOCKER_RUSTFS_NETWORK)
	-docker volume rm $(DOCKER_RUSTFS_VOLUME)

docker-smoke-s3-down:
	@$(DOCKER_SMOKE_COMMON_ENV) \
		$(DOCKER_SMOKE_S3_SCRIPT_ENV) \
		bash scripts/docker/docker-smoke-s3.sh down

docker-rustfs-s3-test:
	@$(DOCKER_SMOKE_COMMON_ENV) \
		$(DOCKER_SMOKE_S3_SCRIPT_ENV) \
		bash scripts/docker/docker-smoke-s3.sh rustfs-s3-test

docker-smoke-s3-probe: docker-rustfs-s3-test

docker-smoke-s3:
	@$(DOCKER_SMOKE_COMMON_ENV) \
		$(DOCKER_SMOKE_S3_SCRIPT_ENV) \
		bash scripts/docker/docker-smoke-s3.sh run

nbd-device-smoke-inner:
	bash scripts/docker/nbd-device-smoke.sh

kernel-smoke-inner: nbd-device-smoke-inner
